# Generated by Django 3.0 on 2022-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220509_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
